// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6kxgJT-Fea8_hdacVUK5fHI2ElzNKZP0',
    appId: '1:672192548950:web:0d8901615815ed57ffebf7',
    messagingSenderId: '672192548950',
    projectId: 'musicservice-ff3d4',
    authDomain: 'musicservice-ff3d4.firebaseapp.com',
    storageBucket: 'musicservice-ff3d4.firebasestorage.app',
    measurementId: 'G-6C7SNW3HB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr2dau0RXMOhSj0OZ91P9K7BQ21L9SSv0',
    appId: '1:672192548950:android:44a196033b64e826ffebf7',
    messagingSenderId: '672192548950',
    projectId: 'musicservice-ff3d4',
    storageBucket: 'musicservice-ff3d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8tQMFUYI27zD-Zo65Y_F2lafA7enm_Ng',
    appId: '1:672192548950:ios:b51ec15581230866ffebf7',
    messagingSenderId: '672192548950',
    projectId: 'musicservice-ff3d4',
    storageBucket: 'musicservice-ff3d4.firebasestorage.app',
    iosBundleId: 'com.example.musicServiceModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8tQMFUYI27zD-Zo65Y_F2lafA7enm_Ng',
    appId: '1:672192548950:ios:b51ec15581230866ffebf7',
    messagingSenderId: '672192548950',
    projectId: 'musicservice-ff3d4',
    storageBucket: 'musicservice-ff3d4.firebasestorage.app',
    iosBundleId: 'com.example.musicServiceModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6kxgJT-Fea8_hdacVUK5fHI2ElzNKZP0',
    appId: '1:672192548950:web:73a3cb448627b81dffebf7',
    messagingSenderId: '672192548950',
    projectId: 'musicservice-ff3d4',
    authDomain: 'musicservice-ff3d4.firebaseapp.com',
    storageBucket: 'musicservice-ff3d4.firebasestorage.app',
    measurementId: 'G-K1N6M3YX3Q',
  );
}
